# Generated by Django 4.2.2 on 2023-06-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, upload_to='static/portfolio/images')),
                ('autor', models.CharField(max_length=40)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
