# Generated by Django 4.2.2 on 2023-06-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('linklusofona', models.CharField(default='1', max_length=1000)),
                ('linklinkedin', models.CharField(default='1', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('acronimo', models.CharField(blank=True, max_length=10)),
                ('ano', models.IntegerField()),
                ('criador', models.CharField(max_length=40)),
                ('logotipo', models.ImageField(upload_to='static/portfolio/images')),
                ('link', models.CharField(max_length=500)),
                ('descricao', models.TextField(max_length=1000)),
                ('existente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('descricao', models.TextField(max_length=1000)),
                ('ects', models.IntegerField()),
                ('ano_letivo', models.CharField(default='1', max_length=20)),
                ('topicos_abordados', models.CharField(default='1', max_length=1000)),
                ('ranking', models.IntegerField()),
                ('link_cadeira', models.CharField(default='1', max_length=1000)),
                ('docente_teorica', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa')),
                ('docentes_praticas', models.ManyToManyField(related_name='professor_pratica', to='portfolio.pessoa')),
                ('linguagens', models.ManyToManyField(blank=True, to='portfolio.tecnologia')),
            ],
        ),
    ]
