# Generated by Django 4.2.2 on 2023-06-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_pessoa_tecnologia_cadeira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='topicos_abordados',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='linklinkedin',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='linklusofona',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='apelido',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
