# Generated by Django 4.2.2 on 2023-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_cadeira_link_cadeira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='link_cadeira',
            field=models.CharField(default='1', max_length=1000),
        ),
    ]
